# KEY 必须是 原版物品的Type 默认计算区域 Base
# 武器类
item:
  wooden_sword:
    section: base
    attribute:
      attack_damage: 4
  stone_sword:
    section: base
    attribute:
      attack_damage: 5
  iron_sword:
    section: base
    attribute:
      attack_damage: 6
  golden_sword:
    section: base
    attribute:
      attack_damage: 4
  diamond_sword:
    section: base
    attribute:
      attack_damage: 7
  netherite_sword:
    section: base
    attribute:
      attack_damage: 8

  wooden_axe:
    section: base
    attribute:
      attack_damage: 7
  stone_axe:
    section: base
    attribute:
      attack_damage: 9
  iron_axe:
    section: base
    attribute:
      attack_damage: 9
  golden_axe:
    section: base
    attribute:
      attack_damage: 7
  diamond_axe:
    section: base
    attribute:
      attack_damage: 9
  netherite_axe:
    section: base
    attribute:
      attack_damage: 10

  # 三叉戟
  trident:
    section: base
    attribute:
      attack_damage: 9
  # 重锤
  mace:
    section: base
    attribute:
      attack_damage: 6

  # 稿
  wooden_pickaxe:
    section: base
    attribute:
      attack_damage: 2
  stone_pickaxe:
    section: base
    attribute:
      attack_damage: 3
  iron_pickaxe:
    section: base
    attribute:
      attack_damage: 4
  golden_pickaxe:
    section: base
    attribute:
      attack_damage: 2
  diamond_pickaxe:
    section: base
    attribute:
      attack_damage: 5
  netherite_pickaxe:
    section: base
    attribute:
      attack_damage: 6

  # 铲子
  wooden_shovel:
    section: base
    attribute:
      attack_damage: 2.5
  stone_shovel:
    section: base
    attribute:
      attack_damage: 3.5
  iron_shovel:
    section: base
    attribute:
      attack_damage: 4.5
  golden_shovel:
    section: base
    attribute:
      attack_damage: 2.5
  diamond_shovel:
    section: base
    attribute:
      attack_damage: 5.5
  netherite_shovel:
    section: base
    attribute:
      attack_damage: 6.5

  # 锄头  # 可以不写
  wooden_hoe:
    section: base
    attribute:
      attack_damage: 1
  stone_hoe:
    section: base
    attribute:
      attack_damage: 1
  golden_hoe:
    section: base
    attribute:
      attack_damage: 1
  iron_hoe:
    section: base
    attribute:
      attack_damage: 1
  diamond_hoe:
    section: base
    attribute:
      attack_damage: 1
  netherite_hoe:
    section: base
    attribute:
      attack_damage: 1

  # 护甲类
  turtle_helmet:
    section: base
    attribute:
      armor: 2

  leather_helmet:
    section: base
    attribute:
      armor: 1
  leather_chestplate:
    section: base
    attribute:
      armor: 3
  leather_leggings:
    section: base
    attribute:
      armor: 2
  leather_boots:
    section: base
    attribute:
      armor: 1

  chainmail_helmet:
    section: base
    attribute:
      armor: 2
  chainmail_chestplate:
    section: base
    attribute:
      armor: 5
  chainmail_leggings:
    section: base
    attribute:
      armor: 4
  chainmail_boots:
    section: base
    attribute:
      armor: 1

  iron_helmet:
    section: base
    attribute:
      armor: 2
  iron_chestplate:
    section: base
    attribute:
      armor: 6
  iron_leggings:
    section: base
    attribute:
      armor: 5
  iron_boots:
    section: base
    attribute:
      armor: 2

  golden_helmet:
    armor: 2
  golden_chestplate:
    section: base
    attribute:
      armor: 5
  golden_leggings:
    section: base
    attribute:
      armor: 3
  golden_boots:
    section: base
    attribute:
      armor: 1

  diamond_helmet:
    section: base
    attribute:
      armor: 3
      armor_toughness: 2
  diamond_chestplate:
    section: base
    attribute:
      armor: 8
      armor_toughness: 2
  diamond_leggings:
    section: base
    attribute:
      armor: 6
      armor_toughness: 2
  diamond_boots:
    section: base
    attribute:
      armor: 3
      armor_toughness: 2

  netherite_helmet:
    section: base
    attribute:
      armor: 3
      armor_toughness: 3
    # knockback_resistance: 不计入
  netherite_chestplate:
    section: base
    attribute:
      armor: 8
      armor_toughness: 3
  netherite_leggings:
    section: base
    attribute:
      armor: 6
      armor_toughness: 3
  netherite_boots:
    section: base
    attribute:
      armor: 3
      armor_toughness: 3

  leather_horse_armor:
    section: base
    attribute:
      armor: 3
  iron_horse_armor:
    section: base
    attribute:
      armor: 5
  golden_horse_armor:
    section: base
    attribute:
      armor: 7
  diamond_horse_armor:
    section: base
    attribute:
      armor: 11
      armor_toughness: 2
  wolf_armor:
    section: base
    attribute:
      armor: 11

potion:
  # 原版药水效果（伤害类药水效果） 其余的没必要
  strength:
    section: base
    attribute:
      attack_damage: 3  # 等级会自动计算（*K）
  weakness:
    section: base
    attribute:
      attack_damage: -4 #
  resistance:
    section: base
    attribute:
      after_armor_reduction: 0.2  # 每级20%防御后伤害减免 (防御前的伤害减免太强大了)
  # 瞬间伤害 仍旧保持真伤

# 原版附魔
# 由于本插件对于玩家攻击事件无感，无法实现 根据伤害来源与类型判定meta是否生效，故无法兼容原版附魔
#enchant:
#  bane_of_arthropods:
#    attack_damage: 2.5  # 截肢杀手每级增加2.5伤害（对节肢动物）
#  blast_protection:
#    after_armor_reduction: 0.08  # 每级减少8%的爆炸伤害
#  breach:
#    after_armor_reduction: -0.15  # 每级减少15%的伤害减免
#  density:
#    attack_damage: 0.5  # 致密每级增加0.5伤害
#  feather_falling:
#    after_armor_reduction: 0.12  # 摔落缓冲每级提供12%的摔落伤害减免
#  fire_protection:
#    after_armor_reduction: 0.08  # 火焰保护每级提供8%的火焰伤害减免
#  impaling:
#    attack_damage: 2.5  # 穿刺每级增加2.5伤害
#  power:
#    section: add
#    attack_damage: 0.5  # 力量每级增加50%的伤害
#  projectile_protection:
#    after_armor_reduction: 0.08  # 弹射物保护每级提供8%的弹射伤害减免
#  protection:
#    after_armor_reduction: 0.04  # 保护每级提供4%的伤害减免
#  sharpness:
#    attack_damage: 0.5  # 锋利每级增加0.5的伤害  # 和原版不一致
#  smite:
#    attack_damage: 2.5  # 亡灵杀手每级增加2.5伤害（对亡灵）


# 当然你的拓展也会生效 - 前提是你的实体类型写对了 :)
# 这里只写护甲，因为生物伤害会以原版的伤害作为插件伤害，在计算护甲，同样的可以拓展
# 不能像原版一样根据状态判断护甲值，可以折中取
living_entity:
  # 僵尸
  zombie:
    section: base
    attribute:
      armor: 2
  # 僵尸猪灵
  zombified_piglin:
    section: base
    attribute:
      armor: 2
  # 僵尸村民
  zombie_villager:
    section: base
    attribute:
      armor: 2
  # 尸壳
  husk:
    section: base
    attribute:
      armor: 2
  # 溺尸
  drowned:
    section: base
    attribute:
      armor: 2
  # 凋零
  wither:
    section: base
    attribute:
      armor: 4
  # 杀手兔
  killer_rabbit:
    section: base
    attribute:
      armor: 8
  # 岩浆怪 - 大
  magma_cube:
    section: base
    attribute:
      armor: 12
  # 潜影贝
  shulker:
    section: base
    attribute:
      armor: 20
  # 拓展一个
  iron_golem:
    section: base
    attribute:
      armor: 80
      attack_damage: 150
