# 所有额外组件都有 updatable 关键词

buff:
  updatable: false # 默认为true
  hold:
    - 自定义buff0
  attack_self:
    - 自定义buff1
  attack:
    - 自定义buff2
  defence_self:
    - 自定义buff3
  defence:
    - 自定义buff4

commands:  # @self会被替换成使用者
  - "give @self minecraft:arrow 5"
  - "effect give @self minecraft:strength 30 1"

damage_type: MELEE  # 默认Other  # 可取值 MELEE,MAGIC,RANGED,ROUGE,SUMMON,OTHER,ENVIRONMENT

terra_durability:
  damage: 5
  max_damage: 10
  break_loss: false

gem:
  inlay_chance: 0.7  # 镶嵌成功概率
  inlay_fail_loss: false
  dismantle_chance: 0.6  # 拆卸成功概率
  dismantle_fail_loss: false

gem_holder:
  limit: 2  # 宝石槽位数量限制
  gems:
    - 宝石物品内部名

level:
  lvl: 0  # 设置等级
  template: 等级模板内部名

terra_meta:
  section: base  # 可选 TIMER, BEFORE_DAMAGE, BASE, ADD, MULTIPLY, FIX, BETWEEN_DAMAGE_AND_DEFENCE, AFTER_DAMAGE, ERROR, INNER
  # 其中 BASE, ADD, MULTIPLY, FIX 表示计算meta 其余的会运行js脚本
  meta:
    damage: 0
    armor: 100
    critical_strike_chance: 0.8
    critical_strike_damage: 1.5
    armor_toughness: 0
    pre_armor_reduction: 0
    after_armor_reduction: 0
    mana_cost: -0.1
    skill_cooldown: -0.1
    # 玩家伤害属性增加
    melee: 0.1  # 战士伤害
    magic: 0.1  # 法师伤害
    ranged: 0.1 # 射手伤害
    rouge: 0.1  # 盗贼伤害
    summon: 0.1 # 召唤伤害
    environment: 0.1  # 环境
    other: 0.01 # 其他

quality:
  group: 可用品质组名
  quality: 默认品质名

skills:
  - skill文件夹配置的Terra内部名称(不是Mythic名称)
  - skill2