# 所有额外组件都有 updatable 关键词

# "自定义buff名称 #持续tick :触发间隔 %给予概率"
buff:
  updatable: true # 默认为true
  hold:  # hold的buff持续时间是永久的 概率100%给予自己 # 非Timer类buff的cd(触发间隔)配置无效
    - "全面增益测试"
  attack_self:  # 攻击后给自己的buff
    - 自定义buff1
  attack:  # 攻击后给对方的buff
    - 自定义buff2
  defence_self:  # 被攻击后给自己的buff
    - 自定义buff3
  defence:  # 被攻击后给对方的buff
    - 自定义buff4

command:  # @self会被替换成使用者
  updatable: true # 默认为true
  content:
    - "give @self minecraft:arrow 5"
    - "effect give @self minecraft:strength 30 1"

damage_type:
  updatable: true # 默认为true
  type: melee  # 默认Other  # 可取值 MELEE,MAGIC,RANGED,ROUGE,SUMMON,OTHER,ENVIRONMENT

terra_durability:
  updatable: true # 默认为true
  damage: 5
  max_damage: 10
  break_loss: false

gem:
  updatable: true # 默认为true
  inlay_chance: 0.7  # 镶嵌成功概率
  inlay_fail_loss: false
  dismantle_chance: 0.6  # 拆卸成功概率
  dismantle_fail_loss: false

gem_holder:
  updatable: true # 默认为true
  limit: 2  # 宝石槽位数量限制
  gems:
    - 宝石物品内部名

level:
  updatable: true # 默认为true
  lvl: 0  # 设置等级
  template: 等级模板内部名

meta:
  updatable: true # 默认为true
  section: base  # 可选 TIMER, BEFORE_DAMAGE, BASE, ADD, MULTIPLY, FIX, BETWEEN_DAMAGE_AND_DEFENCE, AFTER_DAMAGE, ERROR, INNER
  # 其中 BASE, ADD, MULTIPLY, FIX 表示计算meta 其余的会运行js脚本
  attribute:
    attack_damage: 0
    armor: 100
    critical_strike_chance: 0.8
    critical_strike_damage: 1.5
    armor_toughness: 0
    pre_armor_reduction: 0
    after_armor_reduction: 0
    mana_cost: -0.1
    skill_cooldown: -0.1
    # 玩家伤害属性增加
    melee: 0.1  # 战士伤害
    magic: 0.1  # 法师伤害
    ranged: 0.1 # 射手伤害
    rouge: 0.1  # 盗贼伤害
    summon: 0.1 # 召唤伤害
    environment: 0.1  # 环境
    other: 0.01 # 其他

quality:
  updatable: true # 默认为true
  group: 可用品质组名
  default: 默认品质名

skill:
  updatable: true
  content:
    - skill文件夹配置的Terra内部名(不是Mythic名称)

slot:  # meta数据生效的槽位（如果有gem组件则无视--gem除了在槽位上，无法在任何其他位置生效）
  updatable: true # 默认为true
  content: mainhand  # offhand head chest legs feet