# 内部名称不能重复
测试MythicMobs技能-青风斩:
  mythic_name: 青风斩  # 与 mm 技能同名
  cd: 1  # (秒)  # 受到技能cd减免影响
  mana: 10  # 蓝量消耗 （正数为减少，负数增加）
  trigger: right_click  # 不写则不加载

测试蹲下:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: crouch_down

测试起身:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: crouch_up

测试蹲下左键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: crouch_left

测试蹲下右键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: crouch_right

测试左键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: left_click

测试右键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: right_click

测试跳起左键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: jump_left

测试跳起右键:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: jump_right

测试射箭:
  mythic_name: 青风斩
  cd: 1
  mana: 10
  trigger: shoot
